name: beautyhub_mobile
<<<<<<< HEAD
description: BeautyHub Mobile App
=======
description: A new Flutter project.
>>>>>>> fa99272b14a5f642e7c73a7b4a97310e0ede15c4
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  http: ^1.2.0
  shared_preferences: ^2.5.5
  image_picker: ^1.2.2
  cupertino_icons: ^1.0.8
=======

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
>>>>>>> fa99272b14a5f642e7c73a7b4a97310e0ede15c4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true